name: publish-on-release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: mai

      - name: setup-jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: MAVEN_GPG_PRIVATE_KEY
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - uses: qoomon/actions--setup-git@v1
        with:
          user: actor

      - name: publish-on-maven-central
        run: mvn --batch-mode -P osslabz-release clean release:clean release:prepare release:perform
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}